### ISSUE TITLE
Fix bug when video_id doesn't exist

### ISSUE THREAD

**Issue by gpsyrou** [gpsyrou/tube-virality#7]
When running main.go, there is always one line added randomly in the output JSON file, with only a single value ('video_id': {}). Identify why this is happening during the data retrieval method and build case to avoid adding it to the file.

**Comment by limiu82214** [comment]
Hi, I thought that is because your file data "data/metadata/trending/trending_videos_metadata.csv"'s first row is 
`,video_id,video_url,trending_position,trending_date,trending_datetime` .

It happen randomly becuse golang's map is not sort array, so when you use map it maybe randomly.

I can help you if you want to skip the first row of metadata.csv  or you just change your metadat format with delete first row.
:)

**Comment by gpsyrou** [comment]
> 

Fantastic thanks for explaining this. Feel free to submit PRs for any changes or improvements and I am happy to review them.
